// Generated by CoffeeScript 1.4.0

/*
                  Verdict.coffee 0.0.0.0.0.1
 (c) 2011 Radagaisus MIT open-source license
 Inspired by tangle.js - http://worrydream.com/Tangle/

 requirements: jQuery        http://www.jquery.com/
*/


/*
 usage:
  add adjustable_number class if you want some spiffy css
  $("#cookies").numbers
    max: 200
    min: 0
    step: 1
    integer: false
*/


(function() {
  (function($) {
    $.format || ($.format = {});
    $.format.num = function(num) {
      return ('' + num).replace(/(\d+)(\..*)?/, function($0, $1, $2) {
        return $1.replace(/(\d)(?=(\d{3})+$)/g, '$1,') + ($2 || '');
      });
    };
    return $.fn.numbers = function(o) {
      var defaults, number_drag;
      defaults = {
        step: 1,
        integer: true,
        growth: 2
      };
      o = $.extend(defaults, o);
      number_drag = function(elem) {
        elem.css('cursor', 'col-resize');
        elem.mousedown(function(e) {
          var x;
          document.body.onselectstart = function() {
            return false;
          };
          document.body.style.MozUserSelect = "none";
          document.body.onmousedown = function() {
            return false;
          };
          document.body.style.cursor = "col-resize";
          x = e.pageX;
          let val = Number(elem.text().replace(/,/g, ''));
          return $(window).bind('mousemove.numbers', function(change) {
            var dir, _ref, _ref1;
            dir = 2 * (x < change.pageX) - 1;

            val = Math.max(Math.min(val + dir * o.step * (Math.abs(change.pageX - x) / o.growth), (_ref = o.max) != null ? _ref : Infinity), (_ref1 = o.min) != null ? _ref1 : -Infinity);
            if (o.integer != null) {
              // val = Math.floor(val);
            }
            elem.text($.format.num(Math.floor(val)));
            x = change.pageX;
            return elem.trigger('verdict_change', val);
          });
        });
        return $(window).mouseup(function() {
          $(window).unbind('mousemove.numbers');
          document.body.onselectstart = null;
          document.body.style.MozUserSelect = "";
          document.body.onmousedown = null;
          return document.body.style.cursor = "inherit";
        });
      };
      return this.each(function() {
        return number_drag($(this));
      });
    };
  })(window.jQuery);

  /*
   usage:
    add toggle class if you want some spiffy css
    $("#cookies").toggle_select
      list of alternative contents
  */


  (function($) {
    return $.fn.toggle_select = function() {
      var toggle;
      toggle = function(elem) {
        var children, i, _i, _ref;
        children = elem.children();
        for (i = _i = 1, _ref = children.length; 1 <= _ref ? _i < _ref : _i > _ref; i = 1 <= _ref ? ++_i : --_i) {
          children[i].style.display = "none";
        }
        return elem.click(function(e) {
          var n, _j, _ref1;
          children = elem.children();
          n = 0;
          for (i = _j = 0, _ref1 = children.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; i = 0 <= _ref1 ? ++_j : --_j) {
            if (children[i].style.display !== "none") {
              n = (i + 1) % children.length;
            }
            children[i].style.display = "none";
          }
          children[n].style.removeProperty("display");
          return elem.trigger('verdict_change', elem);
        });
      };
      return this.each(function() {
        return toggle($(this));
      });
    };
  })(window.jQuery);

}).call(this);
